export default class MediaItemSource extends String {
	static Billboard: MediaItemSource = 'billboard';
	static Complex: MediaItemSource = 'complex-music';
	static Highsnobiety: MediaItemSource = 'highsnobiety';
	static EliteDaily: MediaItemSource = 'elitedaily';
	static Fader: MediaItemSource = 'fader';
	static FactMag: MediaItemSource = 'factmag';
	static FourPins: MediaItemSource = 'fourpins';
	static Genius: MediaItemSource = 'genius';
	static HotNewHipHop: MediaItemSource = 'hnhh';
	static Hypebeast: MediaItemSource = 'hypebeast';
	static MTV: MediaItemSource = 'mtv-news';
	static Often: MediaItemSource = 'often';
	static Paper: MediaItemSource = 'paper';
	static PigeonsAndPlanes: MediaItemSource = 'pigeonsandplanes';
	static Spotify: MediaItemSource = 'spotify';
	static SpinMusic: MediaItemSource = 'spin-music';
	static SpinNews: MediaItemSource = 'spin-news';
	static Soundcloud: MediaItemSource = 'soundcloud';
	static Youtube: MediaItemSource = 'youtube';
	static VibeNews: MediaItemSource = 'vibe-news';
	static VibeMusic: MediaItemSource = 'vibe-music';
	static Vice: MediaItemSource = 'vice';
	static XXLMag: MediaItemSource = 'xxlmag';
	static TMZ: MediaItemSource = 'tmz';
	static Unknown: MediaItemSource = 'unknown';
};
